name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://126701.w1.wedos.net/subdom/api/
        ftp-username: w126701_api
        ftp-password: ${{ secrets.FTP_PASSWORD }}
